application: pengdi-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.html)
  mime_type: text/html
  static_files: html/\1
  upload: html/(.*\.html)
  application_readable: true

- url: /templates(.*\.html)
  static_files: templates/\1
  upload: templates/(.*\.html)
  application_readable: true

- url: /static(.*)
  static_files: static/\1
  upload: static/(.*)
  application_readable: true

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
